export const CONTACT = {
  mobile: "07375 370444",
  email: "info@highspeccars.com",
  address: "UNIT 1 , CP HOUSE , OTTERSPOOL WAY, WATFORD, WD25 8JJ",
};

export const WORKING_HRS = [
  { day: "Mon - Fri", time: "9:00 am - 6:00 pm" },
  { day: "Saturday", time: "10:00 am - 7:00 pm" },
  { day: "Sunday", time: "11:00 am - 7:00 pm" },
];

export const BODY_STYLE_OPTIONS = [
  "Saloon",
  "Coupe",
  "Estate",
  "Hatchback",
  "Convertible",
  "4x4",
  "Suv",
];

export const DOORS_OPTIONS = ["4 Doors", "2 Doors", "5 Doors", "3 Doors"];

export const COLORS_OPTIONS = [
  "Black",
  "Grey",
  "Yellow",
  "White",
  "Bronze",
  "Blue",
  "Green",
  "Purple",
  "Orange",
  "Silver",
  "Red",
];

export const TRANSMISSION_OPTIONS = [
  "Automatic",
  "Manual",
  "Semi Auto",
];

export const FUEL_TYPE_OPTIONS = [
  "Diesel",
  "Petrol",
  "Petrol Plug-In Hybrid",
];

export const MAKE_OPTIONS = [
  "AC",
  "AK",
  "Abarth",
  "Alfa Romeo",
  "Alpine",
  "Ariel",
  "Aston Martin",
  "Audi",
  "Austin",
  "BMW",
  "BYD",
  "Beauford",
  "Bentley",
  "Bowler",
  "Bramwith",
  "Bugatti",
  "CFMOTO",
  "CUPRA",
  "Cadillac",
  "Caterham",
  "Chesil",
  "Chevrolet",
  "Chrysler",
  "Citroen",
  "Corvette",
  "Crendon",
  "Custom Vehicle",
  "DFSK",
  "DS AUTOMOBILES",
  "Dacia",
  "Daewoo",
  "Daihatsu",
  "Daimler",
  "Datsun",
  "Dax",
  "De Tomaso",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "GWM ORA",
  "Gardener",
  "Genesis Motor",
  "Great Wall",
  "Holden",
  "Honda",
  "Hummer",
  "Hyundai",
  "INEOS",
  "Infiniti",
  "Isuzu",
  "Iveco",
  "Jaguar",
  "Jeep",
  "Jensen",
  "Kia",
  "LEVC",
  "Lada",
  "Lagonda",
  "Lamborghini",
  "Lanchester",
  "Lancia",
  "Land Rover",
  "Lexus",
  "Leyland",
  "Lincoln",
  "Lister",
  "London Taxis International",
  "Lotus",
  "MAXUS",
  "MG",
  "MINI",
  "MOKE",
  "Marcos",
  "Marlin",
  "Maserati",
  "Maybach",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "Mitsubishi",
  "Mitsuoka",
  "Morgan",
  "Morris",
  "NG",
  "Nardini",
  "Nissan",
  "Noble",
  "Opel",
  "Panther",
  "Perodua",
  "Peugeot",
  "Piaggio",
  "Polaris",
  "Polestar",
  "Pontiac",
  "Porsche",
  "Proton",
  "Quantum",
  "Radical",
  "Reliant",
  "Renault",
  "Replica",
  "Riley",
  "Robin Hood",
  "Rolls-Royce",
  "Rover",
  "SEAT",
  "SKODA",
  "Saab",
  "Shelby",
  "Smart",
  "Spyker",
  "SsangYong",
  "Standard",
  "Subaru",
  "Suzuki",
  "TVR",
  "Talbot",
  "Tesla",
  "Tiger",
  "Toyota",
  "Triumph",
  "Ultima",
  "Vauxhall",
  "Volkswagen",
  "Volvo",
  "Westfield",
  "Yamaha",
];
